services:
  promtail:
    image: grafana/promtail:main-1b1e47f
    depends_on:
      - loki
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana
    deploy:
      mode: replicated
      replicas: ${PROMTAIL_REPLICAS:-1}

networks:
  grafana:
    external: true