services:
  grafana:
    image: grafana/grafana:12.0.2
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/provisioning/datasources/ds.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    networks:
      - grafana
      - prometheus
    deploy:
      mode: replicated
      replicas: ${GRAFANA_REPLICAS:-1}

networks:
  grafana:
    name: grafana
  prometheus:
    external: true