services:
  loki:
    image: grafana/loki:main-1b1e47f
    depends_on:
      - grafana
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./config/loki/local-config.yaml:/etc/loki/local-config.yaml
    networks:
      - grafana
    deploy:
      mode: replicated
      replicas: ${LOKI_REPLICAS:-1}

networks:
  grafana:
    external: true